services:
  webtech-backend:
    build: /.
    volumes:
      - webdata:/usr/src/memory-backend/var
    container_name: webtech_backend_server
    ports:
      - 8000:8000

volumes:
  webdata:
    driver: local
    driver_opts:
      type: none
      device: ./var
      o: bind